- generic [active] [ref=e1]:
  - generic [ref=e16]:
    - banner [ref=e17]:
      - img "EVEREST" [ref=e19]
      - generic [ref=e20]:
        - img "Grupo AVAL" [ref=e21]
        - generic [ref=e22]:
          - button "Notificaciones, 2 sin leer" [ref=e23] [cursor=pointer]:
            - generic [aria-hidden] [ref=e24]: "2"
          - button "Accesibilidad" [ref=e25] [cursor=pointer]
          - button "Centro de ayuda" [ref=e32] [cursor=pointer]
        - button "user user" [ref=e34] [cursor=pointer]:
          - generic [ref=e35]: user
          - generic "user" [ref=e36]: U
    - generic [ref=e37]:
      - complementary [ref=e38]:
        - generic [ref=e39]:
          - generic [ref=e40]: MIS HERRAMIENTAS
          - button "Colapsar menú" [ref=e41] [cursor=pointer]
        - navigation "Herramientas asesor" [ref=e42]:
          - link "Consultar Cliente" [ref=e43] [cursor=pointer]:
            - /url: /asesor
          - link "Notificaciones 2 sin leer" [ref=e50] [cursor=pointer]:
            - /url: /asesor/notifications
            - generic [ref=e54]: Notificaciones
            - generic "2 sin leer" [ref=e55]: "2"
          - link "Centro de Ayuda" [ref=e56] [cursor=pointer]:
            - /url: /asesor/ayuda
      - main [ref=e58]:
        - generic [ref=e60]:
          - generic [ref=e63]:
            - heading "Consultar cliente" [level=1] [ref=e64]
            - paragraph [ref=e65]: Selecciona el banco y completa los datos del cliente para validar su identidad.
          - separator [ref=e66]
          - generic [ref=e67]:
            - button [pressed] [ref=e68] [cursor=pointer]:
              - img "Banco de Bogotá" [ref=e69]
            - button [ref=e70] [cursor=pointer]:
              - img "Banco de Occidente" [ref=e71]
            - button [ref=e72] [cursor=pointer]:
              - img "banco popular" [ref=e73]
            - button [ref=e74] [cursor=pointer]:
              - img "AV Villas" [ref=e75]
          - note [ref=e76]:
            - generic [ref=e77]: Solicita al cliente presentar su cédula en formato físico o digital como medio de validación de identidad
          - generic [ref=e78]:
            - generic [ref=e80]:
              - generic [ref=e81]: Tipo de documento *
              - combobox "Tipo de documento *" [ref=e83] [cursor=pointer]:
                - generic [ref=e84]: Selecciona un tipo de documento
            - generic [ref=e87]:
              - generic [ref=e88]: Número de documento *
              - textbox "Número de documento *" [disabled] [ref=e89]:
                - /placeholder: "Ej: 79485236"
            - button "Buscar cliente" [disabled] [ref=e93]: Buscar
        - dialog [ref=e98]:
          - generic [ref=e99]:
            - generic:
              - heading [level=2]
            - button "Cerrar panel" [ref=e100] [cursor=pointer]
          - separator [ref=e104]
        - dialog "Tarjetas Débito" [ref=e106]:
          - generic [ref=e107]:
            - heading "Tarjetas Débito" [level=2] [ref=e109]
            - button "Cerrar panel" [ref=e110] [cursor=pointer]
          - separator [ref=e114]
        - dialog [ref=e116]:
          - generic [ref=e117]:
            - generic:
              - heading [level=2]
            - button "Cerrar panel" [ref=e118] [cursor=pointer]
        - dialog [ref=e123]:
          - generic [ref=e124]:
            - generic:
              - heading [level=2]
            - button "Cerrar panel" [ref=e125] [cursor=pointer]
        - dialog [ref=e130]:
          - generic [ref=e131]:
            - generic:
              - heading [level=2]
            - button "Cerrar panel" [ref=e132] [cursor=pointer]
    - contentinfo "Barra de estado del sistema" [ref=e137]:
      - generic [ref=e138]:
        - generic [ref=e139]:
          - strong [ref=e143]: "Estado del sistema:"
          - text: Conectado
        - generic [ref=e145]:
          - strong [ref=e148]: "Línea de soporte:"
          - text: 01-8000-911-300
        - generic [ref=e150]:
          - strong [ref=e154]: "Mesa de ayuda:"
          - text: soporte@grupoaval.com
      - generic [ref=e155]: API 23ms
  - region "Notificaciones"