package serenityrest.utils;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;

/**
 * Precondicion de ejecucion — 100% data-driven, sin bindings de archivos hardcodeados:
 * 1) Descubre TODOS los .feature bajo features/.
 * 2) Para cada Esquema del escenario cuyo bloque "Ejemplos:" declare
 *    ##@externaldata@<path>@<hoja>, regenera la tabla de Ejemplos leyendo de esa
 *    hoja EXACTAMENTE las columnas que el escenario referencia como <placeholder>.
 * Un escenario nuevo con N filas en su hoja, o una hoja/columna nueva, no requiere
 * tocar esta clase — solo el .feature (marcador + placeholders) y el Excel.
 */
public final class FeatureOutlinePrecondition {

    private static final Path WORKBOOK_PATH = Paths.get("src", "test", "resources", "datadriven", "datadriven.xlsx");
    private static final Path FEATURES_ROOT = Paths.get("src", "test", "resources", "features");
    private static final Path TARGET_FEATURES_ROOT = Paths.get("target", "test-classes", "features");

    private static final DataFormatter FORMATTER = new DataFormatter(Locale.US);
    private static final Pattern PLACEHOLDER = Pattern.compile("<([A-Za-z0-9_]+)>");
    private static final Pattern EXTERNAL_DATA_MARKER = Pattern.compile("##@externaldata@[^@]+@(.+)$");

    private FeatureOutlinePrecondition() {
    }

    public static void main(String[] args) {
        synchronizeFeaturesWithExcel();
    }

    public static synchronized void synchronizeFeaturesWithExcel() {
        List<Path> featureFiles = discoverFeatureFiles();

        try (InputStream inputStream = Files.newInputStream(WORKBOOK_PATH);
             Workbook workbook = WorkbookFactory.create(inputStream)) {
            for (Path featurePath : featureFiles) {
                rewriteFeatureAsOutline(featurePath, workbook);
            }
        } catch (IOException exception) {
            throw new IllegalStateException(
                "No fue posible leer el archivo datadriven: " + WORKBOOK_PATH.toAbsolutePath(),
                exception
            );
        }

        mirrorFeaturesToTarget(featureFiles);
    }

    private static List<Path> discoverFeatureFiles() {
        if (!Files.isDirectory(FEATURES_ROOT)) {
            return List.of();
        }
        try (Stream<Path> walk = Files.walk(FEATURES_ROOT)) {
            return walk.filter(path -> path.toString().endsWith(".feature"))
                .sorted()
                .collect(Collectors.toList());
        } catch (IOException exception) {
            throw new IllegalStateException("No fue posible recorrer " + FEATURES_ROOT.toAbsolutePath(), exception);
        }
    }

    private static void rewriteFeatureAsOutline(Path featurePath, Workbook workbook) {
        List<String> rawLines;
        try {
            rawLines = Files.readAllLines(featurePath, StandardCharsets.UTF_8);
        } catch (IOException exception) {
            throw new IllegalStateException("No fue posible leer el feature: " + featurePath.toAbsolutePath(), exception);
        }

        // La hoja que gobierna cada escenario se lee de su propio marcador ANTES de limpiarlo.
        List<String> sheetByScenarioOrdinal = sheetNameByScenarioOrdinal(rawLines);
        List<String> lines = removeAutoGeneratedExampleBlocks(rawLines);
        List<ScenarioBlock> blocks = parseScenarioBlocks(lines);
        if (blocks.isEmpty()) {
            return;
        }

        List<String> output = new ArrayList<>();
        int cursor = 0;
        for (int ordinal = 0; ordinal < blocks.size(); ordinal++) {
            ScenarioBlock block = blocks.get(ordinal);
            output.addAll(lines.subList(cursor, block.startLine()));

            String sheetName = ordinal < sheetByScenarioOrdinal.size() ? sheetByScenarioOrdinal.get(ordinal) : null;
            if (sheetName != null) {
                output.addAll(renderOutlineBlock(lines, block, workbook, sheetName));
            } else {
                // Sin marcador ##@externaldata — escenario estático, no gestionado por Excel.
                output.addAll(lines.subList(block.startLine(), block.endLineExclusive()));
            }
            cursor = block.endLineExclusive();
        }

        output.addAll(lines.subList(cursor, lines.size()));
        output = normalizeScenarioSpacing(output);

        try {
            Files.write(featurePath, output, StandardCharsets.UTF_8);
        } catch (IOException exception) {
            throw new IllegalStateException("No fue posible actualizar el feature: " + featurePath.toAbsolutePath(), exception);
        }
    }

    private static List<String> sheetNameByScenarioOrdinal(List<String> rawLines) {
        List<String> sheetByOrdinal = new ArrayList<>();
        int currentOrdinal = -1;

        for (String rawLine : rawLines) {
            String trimmed = rawLine.trim();
            if (isScenarioLine(trimmed)) {
                currentOrdinal++;
                sheetByOrdinal.add(null);
                continue;
            }

            Matcher marker = EXTERNAL_DATA_MARKER.matcher(trimmed);
            if (marker.matches() && currentOrdinal >= 0) {
                sheetByOrdinal.set(currentOrdinal, marker.group(1).trim());
            }
        }

        return sheetByOrdinal;
    }

    private static List<String> removeAutoGeneratedExampleBlocks(List<String> lines) {
        List<String> cleaned = new ArrayList<>();

        int i = 0;
        while (i < lines.size()) {
            String trimmed = lines.get(i).trim();

            if ((trimmed.equals("Ejemplos:") || trimmed.equals("Examples:"))
                && i + 1 < lines.size()
                && lines.get(i + 1).trim().startsWith("##@externaldata@")) {

                i += 2;
                while (i < lines.size()) {
                    String rowTrimmed = lines.get(i).trim();
                    if (rowTrimmed.isEmpty() || rowTrimmed.startsWith("|")) {
                        i++;
                        continue;
                    }
                    break;
                }
                continue;
            }

            cleaned.add(lines.get(i));
            i++;
        }

        return cleaned;
    }

    private static List<ScenarioBlock> parseScenarioBlocks(List<String> lines) {
        List<ScenarioBlock> blocks = new ArrayList<>();
        List<Integer> starts = new ArrayList<>();

        for (int i = 0; i < lines.size(); i++) {
            if (isScenarioLine(lines.get(i).trim())) {
                starts.add(i);
            }
        }

        for (int i = 0; i < starts.size(); i++) {
            int start = starts.get(i);
            int nextStart = (i + 1 < starts.size()) ? starts.get(i + 1) : lines.size();
            int endExclusive = endBeforeNextTags(lines, start, nextStart);
            blocks.add(buildBlock(lines, start, endExclusive));
        }

        return blocks;
    }

    private static int endBeforeNextTags(List<String> lines, int currentStart, int nextStart) {
        int end = nextStart;
        while (end > currentStart + 1) {
            String prev = lines.get(end - 1).trim();
            if (prev.isEmpty() || prev.startsWith("@")) {
                end--;
                continue;
            }
            break;
        }
        return end;
    }

    private static ScenarioBlock buildBlock(List<String> lines, int start, int endExclusive) {
        int examplesStart = -1;
        for (int i = start; i < endExclusive; i++) {
            String trimmed = lines.get(i).trim();
            if (trimmed.startsWith("Ejemplos:") || trimmed.startsWith("Examples:")) {
                examplesStart = i;
                break;
            }
        }
        return new ScenarioBlock(start, endExclusive, examplesStart);
    }

    private static boolean isScenarioLine(String trimmedLine) {
        return trimmedLine.startsWith("Escenario:") || trimmedLine.startsWith("Esquema del escenario:");
    }

    private static List<String> renderOutlineBlock(
        List<String> lines,
        ScenarioBlock block,
        Workbook workbook,
        String sheetName
    ) {
        List<String> rendered = new ArrayList<>();

        String scenarioLine = lines.get(block.startLine());
        rendered.add(toScenarioOutlineLine(scenarioLine));

        int contentEnd = block.examplesStartLine() >= 0 ? block.examplesStartLine() : block.endLineExclusive();
        List<String> placeholders = new ArrayList<>();
        for (int i = block.startLine() + 1; i < contentEnd; i++) {
            String line = lines.get(i);
            rendered.add(line);
            collectPlaceholders(line, placeholders);
        }

        if (placeholders.isEmpty()) {
            throw new IllegalStateException(
                "El escenario en la l\u00ednea " + (block.startLine() + 1)
                    + " declara ##@externaldata@..@" + sheetName + " pero no usa ning\u00fan <placeholder>."
            );
        }

        if (!rendered.isEmpty() && !rendered.get(rendered.size() - 1).trim().isEmpty()) {
            rendered.add("");
        }

        List<List<String>> rows = readExampleRows(workbook, sheetName, placeholders);

        rendered.add("    Ejemplos:");
        rendered.add("      ##@externaldata@src/test/resources/datadriven/datadriven.xlsx@" + sheetName);
        rendered.add("      | " + String.join(" | ", placeholders) + " |");
        for (List<String> row : rows) {
            rendered.add("      |" + String.join("|", row) + "|");
        }

        return rendered;
    }

    private static void collectPlaceholders(String line, List<String> placeholders) {
        Matcher matcher = PLACEHOLDER.matcher(line);
        while (matcher.find()) {
            String name = matcher.group(1);
            if (!placeholders.contains(name)) {
                placeholders.add(name);
            }
        }
    }

    private static List<List<String>> readExampleRows(Workbook workbook, String sheetName, List<String> columnNames) {
        Sheet sheet = workbook.getSheet(sheetName);
        if (sheet == null) {
            throw new IllegalStateException("No existe la hoja '" + sheetName + "' en datadriven.xlsx");
        }

        Row headerRow = sheet.getRow(0);
        if (headerRow == null) {
            throw new IllegalStateException("La hoja '" + sheetName + "' no tiene fila de encabezados");
        }

        Map<String, Integer> columnIndexByHeader = new LinkedHashMap<>();
        for (int col = 0; col < headerRow.getLastCellNum(); col++) {
            String header = FORMATTER.formatCellValue(headerRow.getCell(col)).trim();
            if (!header.isBlank()) {
                columnIndexByHeader.put(header, col);
            }
        }

        List<Integer> columnIndexes = new ArrayList<>();
        for (String columnName : columnNames) {
            Integer index = columnIndexByHeader.get(columnName);
            if (index == null) {
                throw new IllegalStateException(
                    "La hoja '" + sheetName + "' no tiene la columna '" + columnName
                        + "' requerida por el <placeholder> del escenario."
                );
            }
            columnIndexes.add(index);
        }

        List<List<String>> rows = new ArrayList<>();
        for (int rowIndex = 1; rowIndex <= sheet.getLastRowNum(); rowIndex++) {
            Row row = sheet.getRow(rowIndex);
            if (row == null || !hasAnyValue(row)) {
                continue;
            }
            List<String> values = new ArrayList<>();
            for (int columnIndex : columnIndexes) {
                values.add(FORMATTER.formatCellValue(row.getCell(columnIndex)).trim());
            }
            rows.add(values);
        }

        if (rows.isEmpty()) {
            throw new IllegalStateException("La hoja '" + sheetName + "' no tiene filas de datos.");
        }
        return rows;
    }

    private static boolean hasAnyValue(Row row) {
        short firstCell = row.getFirstCellNum();
        short lastCell = row.getLastCellNum();
        if (firstCell < 0 || lastCell < 0) {
            return false;
        }

        for (int col = firstCell; col < lastCell; col++) {
            String value = FORMATTER.formatCellValue(row.getCell(col)).trim();
            if (!value.isEmpty()) {
                return true;
            }
        }
        return false;
    }

    private static String toScenarioOutlineLine(String line) {
        if (line.contains("Escenario:")) {
            return line.replace("Escenario:", "Esquema del escenario:");
        }
        return line;
    }

    private static List<String> normalizeScenarioSpacing(List<String> lines) {
        List<String> normalized = new ArrayList<>();

        for (int i = 0; i < lines.size(); i++) {
            String current = lines.get(i);
            if (current.trim().isEmpty() && i > 0 && i + 1 < lines.size()) {
                String prev = lines.get(i - 1).trim();
                String next = lines.get(i + 1).trim();
                if (prev.startsWith("@") && isScenarioLine(next)) {
                    continue;
                }
            }
            normalized.add(current);
        }

        return normalized;
    }

    private static void mirrorFeaturesToTarget(List<Path> featureFiles) {
        if (!Files.exists(TARGET_FEATURES_ROOT)) {
            return;
        }

        try {
            for (Path source : featureFiles) {
                Path relative = FEATURES_ROOT.relativize(source);
                Path target = TARGET_FEATURES_ROOT.resolve(relative);
                Files.createDirectories(target.getParent());
                Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
            }
        } catch (IOException exception) {
            throw new IllegalStateException("No fue posible sincronizar features en target/test-classes", exception);
        }
    }

    private record ScenarioBlock(int startLine, int endLineExclusive, int examplesStartLine) {
    }
}
